# ----------------- Backend ----------------- #          
backend = "glx";
vsync = true;
use-damage = false;

# ----------------- Corners ----------------- #
corner-radius = 8;

# ----------------- Fading ----------------- #
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 8;

# ----------------- Opacity ----------------- #
frame-opacity = 0.8;
detect-client-opacity = true;

# ----------------- Blur ----------------- #
blur-method = "dual_kawase";
blur-strength = 3;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = false;

# ----------------- General Settings ----------------- #
detect-rounded-corners = true;
detect-transient = true;
dbe = false;
log-level = "warn";

# ----------------- Rules ----------------- #
rules: ({
    # Plank — no efek sama sekali
    match = "class_g = 'Plank'";
    blur-background = false;
    shadow = false;
    fade = false;
    opacity = 1.0;
    corner-radius = 0;
}, {
    # Panel XFCE — blur aktif, sudut kotak
    match = "window_type = 'dock' && !(class_g = 'Plank')";
    blur-background = true;
    shadow = false;
    fade = false;
    opacity = 0.85;
    corner-radius = 0;
}, {
    # Desktop — no efek
    match = "window_type = 'desktop'";
    blur-background = false;
    shadow = false;
    fade = false;
    corner-radius = 0;
}, {
    # Screenshot tools — no blur
    match = "class_g = 'Xfce4-screenshooter' || class_g = 'flameshot' || class_g = 'gnome-screenshot' || class_g = 'slop'";
    blur-background = false;
    shadow = false;
    fade = false;
}, {
    # GTK frame extents — no blur
    match = "_GTK_FRAME_EXTENTS@";
    blur-background = false;
    shadow = false;
}, {
    # Conky — no efek
    match = "class_g = 'Conky'";
    blur-background = false;
    shadow = false;
    fade = false;
}, {
    # Kitty terminal
    match = "class_g = 'kitty'";
    blur-background = true;
    shadow = true;
    fade = true;
}, {
    # Alacritty
    match = "class_g = 'Alacritty'";
    blur-background = true;
    shadow = true;
    fade = true;
}, {
    # XFCE Terminal
    match = "class_g = 'Xfce4-terminal'";
    blur-background = true;
    shadow = true;
    fade = true;
}, {
    # Tooltip
    match = "window_type = 'tooltip'";
    fade = false;
    shadow = true;
    opacity = 0.75;
    blur-background = false;
}, {
    # Popup & dropdown menu
    match = "window_type = 'popup_menu' || window_type = 'dropdown_menu'";
    blur-background = false;
    fade = false;
    shadow = false;
}, {
    # Notifikasi
    match = "name = 'Notification' || class_g ?= 'Notify-osd'";
    shadow = false;
    blur-background = false;
    fade = false;
})
