add_newline = false
palette = "catppuccin_mocha"

# Format prompt dengan pendeteksi bahasa pemrograman
format = "$directory$git_branch$git_status$golang$nodejs$bun$java$character"

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"

[directory]
style = "bold #89b4fa"
truncation_length = 2
truncate_to_repo = false

[git_branch]
symbol = " "
style = "bold #f5c2e7"

[git_status]
style = "bold #f9e2af"

# ==========================================
# LANGUAGE & RUNTIME AUTO-DETECT
# ==========================================
[golang]
symbol = " "
style = "bold #74c7ec"
format = "via [$symbol($version )]($style)"

[nodejs]
symbol = " "
style = "bold #a6e3a1"
format = "via [$symbol($version )]($style)"

[bun]
symbol = "󰏗 "
style = "bold #f5e0dc"
format = "via [$symbol($version )]($style)"

[java]
symbol = " "
style = "bold #fab387"
format = "via [$symbol($version )]($style)"

# ==========================================
# PALETTE CATPPUCCIN MOCHA
# ==========================================
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
