#~/.tmux.conf

#--------ESSENTIAL SETTINGS-----------#

# Increase scrollback buffer
set -g history-limit 50000
 
# Enable Mouse Support
set -g mouse on

# Set terminal with proper colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"


#--------APPEARANCE----------#

# set status bar position
set -g status-position top
